l = []
n = 0
n2 = 0
a = []
l2 = []
done = False
sit = []

def place_words(tmp):
	for i in range(0,len(tmp)):
		tmp[i]=tmp[i].upper()
	global l
	global n
	global n2
	global a
	global done
	global sit
	l = tmp
	n = len(l[0])
	n2 = len(l)
	a = [0]*n
	func(0)
	ret = False
	if done:
		ret=sit
	l = []
	n = 0
	n2 = 0
	a = []
	l2 = []
	done = False
	#sit = []
	return ret

def func(x):
	global a
	global n
	global n2
	global sit
	global done
	if(x>=n):
		place(x)
		if kontrol():
			done = True
			sit = l2
		return
	for i in range(0,n2):
		if done:
			return
		a[x]=i
		place(x)
		if kontrol():
			func(x+1)
	return
	
def place(x):
	global a
	global n
	global l2
	global sit
	global done
	l2 = []
	for i in range(0,x):
		l2.append(l[a[i]])

def kontrol():
	global a
	global n
	global n2
	global l
	global l2
	say = [0]*(n2+1)
	for i in l2:
		for j in range(0,n2):
			if i==l[j][0:len(i):]:
				say[j]+=1
				if say[j]>1 and len(i)==n:
					return False
	for i in range(0,n):
		s = ""
		flag2 = False
		for j in range(0,len(l2)):
			s = s+l2[j][i]
		for j in range(0,n2):
			if(s==l[j][0:len(s):]):
				flag2 = True
				say[j]+=1
				if say[j]>1 and len(s)==n:
					return False
		if not flag2:
			return False
	return True

print place_words(['KGAPEYPXWKCHZOKZGAGYOUVYD', 'KGMMAZBDAPMZKYFBPSJHTFTRW', 'QLGWFOGMBUJDYRDZUTLBNGVLN', 'DHCUGJQFDKDUTQTNTDHJFVDNC', 'RJQFDQTCTQMSBXQKTDJVFVCOP', 'GHOJAGRJGKDMOHINEXEUKDQYO', 'NHSSMSSQWHGQCTXTANLNZGDRY', 'ORCALXJQSVOYYSCWLUFLVMYZW', 'CCUXESOUZYBYFUIEBELQRWLYZ', 'OKTVLBJTPGNGXIYDUGAFGWLHR', 'ZVZQHHTUQGHFXPPASKKYPPUTL', 'NDUIJOCWBXITHLNXAZSIKPSEO', 'QPNWCWFZLPMYQXCIMPEYMFWAA', 'RJYWTVDXFEDCQPRJYWCPAAFBL', 'GOFQRFMYWCKNJODSZCKKWSWCZ', 'HIIXPHVDSMCTJEQQPAEBLHEUD', 'FPPEWHQEXYRIVHKOKTPWZBOSX', 'EUWMYKPSPOKAEETSSSJSNLXBI', 'JIZVJZBFIZWXFJLHEZPXKCYCY', 'WEQYGDTTLWGQBSRBPYWWAOBCS', 'XGNPWTRXYKMNZJDEKLFZUIEEX', 'MLBIOETWQPGMDVVCPRESBSGNJ', 'WGPEGCFYJOAAQLMKNUSETLNCV', 'WPDXOJXJWJFEUTYKIFDLRDJNP', 'EAWECPEXWUHLPGHFKFOHSILLM', 'FXXZZKQKEAGKBIZUWNWCMMGFC', 'OXBQQVDDBIOCFNTFXQFNQWBFP', 'JVZWWEIUYNNSVBUDQGGHEKWXD', 'TSUMBYSZEDOZUOPCQHSGDHQLQ', 'UFCYPWSKWVKNXKJJYFTEEGLQK', 'YHFABSNMCXKRCVNUTIDSCTFYL', 'NRNOXMUKXLZDIFJCHYOFQCUNB', 'KFSNFZMLXCRJOCUIKMHKMCJKO', 'KDWHMQVKNYIHNBKISZHEHSBSL', 'HKXPJPLDEKFHIZHGVOKDGUNCD', 'JTKZXEWSTVLQFSFWUJHKYRLUF', 'QYMKUZRESVVKVZUITYOBHQHWL', 'OZXBRBXSHOHNNEILEJGKYERVS', 'COZGDWDJBAGDQARZSLFFSOTIU', 'TTFRFANUJZJEQFHCYQLMAGEGQ', 'CKRNHGQVDKKUIMVXOKUVPXUXV', 'DWMFABSZOXCGCEVOPODSLKRWR', 'MGKYCIMCQUJQXNUUFDNHAJZYZ', 'DNGMDRGAGKRGWHDFHGCIAHLBA', 'ZDNDRBPFBDAZPDVOIXMKWRNLW', 'SGEDKRKWUZFUFQMXSEFJBOZUW', 'YDAUNBCSNXACDDAWSXXKDZMMQ', 'OTXNYPBAQRSSZXCEZZOWPSRUN', 'WNRWLICLMVLZBESSXELLTRVFY', 'ALZCTWONGHFMJRGKHDXMGMLER', 'GPELFXQNLDXWIHDUQBGNJTMZB', 'SUSKMNVRTUHJWHYPLIIGFKGTM', 'GBKWVHEBDGZSZBJRHWCQCNISB', 'KKOGXCJHGGCNFERSJFOTJDLDF', 'IYZCRKVARVUXLITMPRRKMYSIV'])
